/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    reservations: Reservation;
    owners: Owner;
    boats: Boat;
    'event-types': EventType;
    'boat-types': BoatType;
    extras: Extra;
    hero: Hero;
    media: Media;
    menu: Menu;
    footer: Footer;
    users: User;
    routes: Route;
    locations: Location;
    reviews: Review;
    subscribers: Subscriber;
    coupons: Coupon;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    owners: OwnersSelect<false> | OwnersSelect<true>;
    boats: BoatsSelect<false> | BoatsSelect<true>;
    'event-types': EventTypesSelect<false> | EventTypesSelect<true>;
    'boat-types': BoatTypesSelect<false> | BoatTypesSelect<true>;
    extras: ExtrasSelect<false> | ExtrasSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    routes: RoutesSelect<false> | RoutesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: string;
  boat?: (string | null) | Boat;
  /**
   * Auto-copied from the selected boat location (used in client emails).
   */
  departureLocation?: string | null;
  paymentMethod: 'full' | 'installments';
  /**
   * Number of installments AFTER the down payment (e.g. 1, 2, 3, 4)
   */
  numberOfInstallments?: number | null;
  /**
   * Optional. If empty, the system defaults to an even split across (installments + 1).
   */
  downPaymentAmount?: number | null;
  guests?: number | null;
  user?: string | null;
  guestEmail?: string | null;
  countryCode:
    | '+93'
    | '+358'
    | '+355'
    | '+213'
    | '+1'
    | '+376'
    | '+244'
    | '+54'
    | '+374'
    | '+297'
    | '+247'
    | '+61'
    | '+43'
    | '+994'
    | '+973'
    | '+880'
    | '+375'
    | '+32'
    | '+501'
    | '+229'
    | '+975'
    | '+591'
    | '+387'
    | '+267'
    | '+55'
    | '+246'
    | '+673'
    | '+359'
    | '+226'
    | '+257'
    | '+855'
    | '+237'
    | '+238'
    | '+599'
    | '+236'
    | '+235'
    | '+56'
    | '+86'
    | '+57'
    | '+269'
    | '+242'
    | '+243'
    | '+682'
    | '+506'
    | '+225'
    | '+385'
    | '+53'
    | '+357'
    | '+420'
    | '+45'
    | '+253'
    | '+593'
    | '+20'
    | '+503'
    | '+240'
    | '+291'
    | '+372'
    | '+268'
    | '+251'
    | '+500'
    | '+298'
    | '+679'
    | '+33'
    | '+594'
    | '+689'
    | '+241'
    | '+220'
    | '+995'
    | '+49'
    | '+233'
    | '+350'
    | '+30'
    | '+299'
    | '+590'
    | '+502'
    | '+44'
    | '+224'
    | '+245'
    | '+592'
    | '+509'
    | '+504'
    | '+852'
    | '+36'
    | '+354'
    | '+91'
    | '+62'
    | '+98'
    | '+964'
    | '+353'
    | '+972'
    | '+39'
    | '+81'
    | '+962'
    | '+7'
    | '+254'
    | '+686'
    | '+383'
    | '+965'
    | '+996'
    | '+856'
    | '+371'
    | '+961'
    | '+266'
    | '+231'
    | '+218'
    | '+423'
    | '+370'
    | '+352'
    | '+853'
    | '+261'
    | '+265'
    | '+60'
    | '+960'
    | '+223'
    | '+356'
    | '+692'
    | '+596'
    | '+222'
    | '+230'
    | '+262'
    | '+52'
    | '+691'
    | '+373'
    | '+377'
    | '+976'
    | '+382'
    | '+212'
    | '+258'
    | '+95'
    | '+264'
    | '+674'
    | '+977'
    | '+31'
    | '+687'
    | '+64'
    | '+505'
    | '+227'
    | '+234'
    | '+683'
    | '+672'
    | '+850'
    | '+389'
    | '+47'
    | '+968'
    | '+92'
    | '+680'
    | '+970'
    | '+507'
    | '+675'
    | '+595'
    | '+51'
    | '+63'
    | '+48'
    | '+351'
    | '+974'
    | '+40'
    | '+250'
    | '+685'
    | '+378'
    | '+239'
    | '+966'
    | '+221'
    | '+381'
    | '+248'
    | '+232'
    | '+65'
    | '+421'
    | '+386'
    | '+677'
    | '+252'
    | '+27'
    | '+82'
    | '+211'
    | '+34'
    | '+94'
    | '+290'
    | '+508'
    | '+249'
    | '+597'
    | '+46'
    | '+41'
    | '+963'
    | '+886'
    | '+992'
    | '+255'
    | '+66'
    | '+670'
    | '+228'
    | '+690'
    | '+676'
    | '+216'
    | '+90'
    | '+993'
    | '+688'
    | '+256'
    | '+380'
    | '+971'
    | '+598'
    | '+998'
    | '+678'
    | '+58'
    | '+84'
    | '+681'
    | '+967'
    | '+260'
    | '+263';
  guestPhone: string;
  startTime: string;
  endTime: string;
  status?: ('pending' | 'confirmed' | 'cancelled' | 'awaiting payment') | null;
  paymentLinkId?: string | null;
  paymentLink?: string | null;
  /**
   * Calculated based on duration and boat pricing
   */
  totalPrice?: number | null;
  method: 'Mamo Pay' | 'Bank Transfer' | 'Cash';
  /**
   * Instalment of all payments made for this reservation
   */
  payments?:
    | {
        id?: string | null;
        kind?: ('full' | 'downpayment' | 'installment') | null;
        installmentStage?: ('paid' | 'ready_to_be_installed' | 'installed_ready_to_be_paid') | null;
        createdAt?: string | null;
        installedAt?: string | null;
        paidAt?: string | null;
        amount: number;
        method: 'Mamo Pay' | 'Bank Transfer' | 'Cash';
        date: string;
        status: 'pending' | 'completed' | 'failed' | 'refunded';
        /**
         * Balance remaining after this payment
         */
        balance?: number | null;
        paymentLink?: string | null;
        paymentLinkId?: string | null;
        /**
         * Any additional notes about this payment
         */
        notes?: string | null;
      }[]
    | null;
  /**
   * Booking ID from reservations processor
   */
  transactionId?: string | null;
  specialRequests?: string | null;
  extras?:
    | {
        extra: string | Extra;
        quantity: number;
        /**
         * Price per unit at time of booking
         */
        unitPrice: number;
        id?: string | null;
      }[]
    | null;
  otherExtras?:
    | {
        name: string;
        price: number;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Applied coupon for this reservation (set from frontend)
   */
  coupon?: (string | null) | Coupon;
  /**
   * Coupon code snapshot at time of booking
   */
  couponCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boats".
 */
export interface Boat {
  id: string;
  slug: string;
  owner?: (string | null) | Owner;
  name: string;
  location?: (string | null) | Location;
  price: number;
  salePrice?: number | null;
  priceDay: number;
  minHours: number;
  /**
   * Set advanced minimum hour rules and special event packages.
   */
  advancedMinHours?:
    | {
        /**
         * Choose whether this rule sets a minimum number of hours or a special event package.
         */
        ruleType: 'minHours' | 'specialEvent';
        /**
         * Choose specific day(s), weekdays/weekend, or All Days. For Special Event rules, you can also switch to a specific date range below.
         */
        days?:
          | (
              | 'all'
              | 'monday'
              | 'tuesday'
              | 'wednesday'
              | 'thursday'
              | 'friday'
              | 'saturday'
              | 'sunday'
              | 'weekdays'
              | 'weekend'
            )[]
          | null;
        timeRange: {
          type: 'allDay' | 'custom';
          /**
           * Select start time
           */
          startTime?: string | null;
          /**
           * Select end time
           */
          endTime?: string | null;
        };
        /**
         * This controls the minimum number of hours when this rule applies.
         */
        minHours?: ('1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '12' | '24') | null;
        /**
         * e.g. New Year’s Eve, Eid Weekend, National Day, etc.
         */
        specialEventName?: string | null;
        /**
         * Choose whether this event uses day-based rules (e.g. weekends) or an exact date / date range.
         */
        dateMode?: ('day' | 'date') | null;
        /**
         * Event start date (inclusive).
         */
        startDate?: string | null;
        /**
         * Event end date (inclusive).
         */
        endDate?: string | null;
        /**
         * How many hours are included in this special event package.
         */
        packageHours?: ('1' | '2' | '3' | '4' | '5' | '6' | '8' | '10' | '12') | null;
        /**
         * Total price for the package (for the package hours). The system will derive an hourly rate from this.
         */
        packagePrice?: number | null;
        id?: string | null;
      }[]
    | null;
  boatSpecifications: {
    type: 'Yacht' | 'Sailboat' | 'Speedboat' | 'Pontoon' | 'Catamaran' | 'Luxury Yachts' | 'Other';
    manufacture: string;
    refit?: string | null;
    length: string;
    capacity: number;
    sleeps: string;
    bathrooms: string;
    crew?: number | null;
    /**
     * Detailed description of the extra service
     */
    description?: string | null;
  };
  keyFeatures?:
    | {
        feature: string;
        included?: boolean | null;
        id?: string | null;
      }[]
    | null;
  amenities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  additionalServices?:
    | {
        service: string;
        file?: (string | null) | Media;
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Select predefined routes for this boat
   */
  routes?: (string | Route)[] | null;
  media: string | Media;
  gallery?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  boatSpecific?:
    | {
        faq?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Note: Only one Fixed or Percentage discount can be active at a time.
   */
  discounts?:
    | {
        /**
         * Only one Fixed or Percentage discount can be active at a time.
         */
        type: 'fixed' | 'percentage' | 'b1g1' | 'bulk_fixed' | 'bulk_percentage';
        variable?: number | null;
        /**
         * Enter amount - fixed value or percentage based on discount type
         */
        amount: number;
        startDate: string;
        endDate: string;
        id?: string | null;
      }[]
    | null;
  surgePricing?: string | null;
  /**
   * Automatically calculated average rating
   */
  averageRating?: number | null;
  /**
   * Total approved reviews
   */
  reviewCount?: number | null;
  specialEventTags?: (string | EventType)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "owners".
 */
export interface Owner {
  id: string;
  name: string;
  countryCode:
    | '+93'
    | '+358'
    | '+355'
    | '+213'
    | '+1'
    | '+376'
    | '+244'
    | '+54'
    | '+374'
    | '+297'
    | '+247'
    | '+61'
    | '+43'
    | '+994'
    | '+973'
    | '+880'
    | '+375'
    | '+32'
    | '+501'
    | '+229'
    | '+975'
    | '+591'
    | '+387'
    | '+267'
    | '+55'
    | '+246'
    | '+673'
    | '+359'
    | '+226'
    | '+257'
    | '+855'
    | '+237'
    | '+238'
    | '+599'
    | '+236'
    | '+235'
    | '+56'
    | '+86'
    | '+57'
    | '+269'
    | '+242'
    | '+243'
    | '+682'
    | '+506'
    | '+225'
    | '+385'
    | '+53'
    | '+357'
    | '+420'
    | '+45'
    | '+253'
    | '+593'
    | '+20'
    | '+503'
    | '+240'
    | '+291'
    | '+372'
    | '+268'
    | '+251'
    | '+500'
    | '+298'
    | '+679'
    | '+33'
    | '+594'
    | '+689'
    | '+241'
    | '+220'
    | '+995'
    | '+49'
    | '+233'
    | '+350'
    | '+30'
    | '+299'
    | '+590'
    | '+502'
    | '+44'
    | '+224'
    | '+245'
    | '+592'
    | '+509'
    | '+504'
    | '+852'
    | '+36'
    | '+354'
    | '+91'
    | '+62'
    | '+98'
    | '+964'
    | '+353'
    | '+972'
    | '+39'
    | '+81'
    | '+962'
    | '+7'
    | '+254'
    | '+686'
    | '+383'
    | '+965'
    | '+996'
    | '+856'
    | '+371'
    | '+961'
    | '+266'
    | '+231'
    | '+218'
    | '+423'
    | '+370'
    | '+352'
    | '+853'
    | '+261'
    | '+265'
    | '+60'
    | '+960'
    | '+223'
    | '+356'
    | '+692'
    | '+596'
    | '+222'
    | '+230'
    | '+262'
    | '+52'
    | '+691'
    | '+373'
    | '+377'
    | '+976'
    | '+382'
    | '+212'
    | '+258'
    | '+95'
    | '+264'
    | '+674'
    | '+977'
    | '+31'
    | '+687'
    | '+64'
    | '+505'
    | '+227'
    | '+234'
    | '+683'
    | '+672'
    | '+850'
    | '+389'
    | '+47'
    | '+968'
    | '+92'
    | '+680'
    | '+970'
    | '+507'
    | '+675'
    | '+595'
    | '+51'
    | '+63'
    | '+48'
    | '+351'
    | '+974'
    | '+40'
    | '+250'
    | '+685'
    | '+378'
    | '+239'
    | '+966'
    | '+221'
    | '+381'
    | '+248'
    | '+232'
    | '+65'
    | '+421'
    | '+386'
    | '+677'
    | '+252'
    | '+27'
    | '+82'
    | '+211'
    | '+34'
    | '+94'
    | '+290'
    | '+508'
    | '+249'
    | '+597'
    | '+46'
    | '+41'
    | '+963'
    | '+886'
    | '+992'
    | '+255'
    | '+66'
    | '+670'
    | '+228'
    | '+690'
    | '+676'
    | '+216'
    | '+90'
    | '+993'
    | '+688'
    | '+256'
    | '+380'
    | '+971'
    | '+598'
    | '+998'
    | '+678'
    | '+58'
    | '+84'
    | '+681'
    | '+967'
    | '+260'
    | '+263';
  contactNumber: string;
  address: {
    streetLine1: string;
    streetLine2?: string | null;
    city: string;
    state?: string | null;
    postalCode?: string | null;
    country:
      | 'AC'
      | 'AD'
      | 'AE'
      | 'AF'
      | 'AG'
      | 'AI'
      | 'AL'
      | 'AM'
      | 'AO'
      | 'AR'
      | 'AS'
      | 'AT'
      | 'AU'
      | 'AW'
      | 'AX'
      | 'AZ'
      | 'BA'
      | 'BB'
      | 'BD'
      | 'BE'
      | 'BF'
      | 'BG'
      | 'BH'
      | 'BI'
      | 'BJ'
      | 'BL'
      | 'BM'
      | 'BN'
      | 'BO'
      | 'BQ'
      | 'BR'
      | 'BS'
      | 'BT'
      | 'BW'
      | 'BY'
      | 'BZ'
      | 'CA'
      | 'CC'
      | 'CD'
      | 'CF'
      | 'CG'
      | 'CH'
      | 'CI'
      | 'CK'
      | 'CL'
      | 'CM'
      | 'CN'
      | 'CO'
      | 'CR'
      | 'CU'
      | 'CV'
      | 'CW'
      | 'CX'
      | 'CY'
      | 'CZ'
      | 'DE'
      | 'DJ'
      | 'DK'
      | 'DM'
      | 'DO'
      | 'DZ'
      | 'EC'
      | 'EE'
      | 'EG'
      | 'EH'
      | 'ER'
      | 'ES'
      | 'ET'
      | 'FI'
      | 'FJ'
      | 'FK'
      | 'FM'
      | 'FO'
      | 'FR'
      | 'GA'
      | 'GB'
      | 'GD'
      | 'GE'
      | 'GF'
      | 'GG'
      | 'GH'
      | 'GI'
      | 'GL'
      | 'GM'
      | 'GN'
      | 'GP'
      | 'GQ'
      | 'GR'
      | 'GT'
      | 'GU'
      | 'GW'
      | 'GY'
      | 'HK'
      | 'HN'
      | 'HR'
      | 'HT'
      | 'HU'
      | 'ID'
      | 'IE'
      | 'IL'
      | 'IM'
      | 'IN'
      | 'IO'
      | 'IQ'
      | 'IR'
      | 'IS'
      | 'IT'
      | 'JE'
      | 'JM'
      | 'JO'
      | 'JP'
      | 'KE'
      | 'KG'
      | 'KH'
      | 'KI'
      | 'KM'
      | 'KN'
      | 'KP'
      | 'KR'
      | 'KW'
      | 'KY'
      | 'KZ'
      | 'LA'
      | 'LB'
      | 'LC'
      | 'LI'
      | 'LK'
      | 'LR'
      | 'LS'
      | 'LT'
      | 'LU'
      | 'LV'
      | 'LY'
      | 'MA'
      | 'MC'
      | 'MD'
      | 'ME'
      | 'MF'
      | 'MG'
      | 'MH'
      | 'MK'
      | 'ML'
      | 'MM'
      | 'MN'
      | 'MO'
      | 'MP'
      | 'MQ'
      | 'MR'
      | 'MS'
      | 'MT'
      | 'MU'
      | 'MV'
      | 'MW'
      | 'MX'
      | 'MY'
      | 'MZ'
      | 'NA'
      | 'NC'
      | 'NE'
      | 'NF'
      | 'NG'
      | 'NI'
      | 'NL'
      | 'NO'
      | 'NP'
      | 'NR'
      | 'NU'
      | 'NZ'
      | 'OM'
      | 'PA'
      | 'PE'
      | 'PF'
      | 'PG'
      | 'PH'
      | 'PK'
      | 'PL'
      | 'PM'
      | 'PR'
      | 'PS'
      | 'PT'
      | 'PW'
      | 'PY'
      | 'QA'
      | 'RE'
      | 'RO'
      | 'RS'
      | 'RU'
      | 'RW'
      | 'SA'
      | 'SB'
      | 'SC'
      | 'SD'
      | 'SE'
      | 'SG'
      | 'SH'
      | 'SI'
      | 'SJ'
      | 'SK'
      | 'SL'
      | 'SM'
      | 'SN'
      | 'SO'
      | 'SR'
      | 'SS'
      | 'ST'
      | 'SV'
      | 'SX'
      | 'SY'
      | 'SZ'
      | 'TA'
      | 'TC'
      | 'TD'
      | 'TG'
      | 'TH'
      | 'TJ'
      | 'TK'
      | 'TL'
      | 'TM'
      | 'TN'
      | 'TO'
      | 'TR'
      | 'TT'
      | 'TV'
      | 'TW'
      | 'TZ'
      | 'UA'
      | 'UG'
      | 'US'
      | 'UY'
      | 'UZ'
      | 'VA'
      | 'VC'
      | 'VE'
      | 'VG'
      | 'VI'
      | 'VN'
      | 'VU'
      | 'WF'
      | 'WS'
      | 'XK'
      | 'YE'
      | 'YT'
      | 'ZA'
      | 'ZM'
      | 'ZW';
  };
  email: string;
  bankDetails?: {
    accountName?: string | null;
    iban?: string | null;
    bankName?: string | null;
    country?:
      | (
          | 'AC'
          | 'AD'
          | 'AE'
          | 'AF'
          | 'AG'
          | 'AI'
          | 'AL'
          | 'AM'
          | 'AO'
          | 'AR'
          | 'AS'
          | 'AT'
          | 'AU'
          | 'AW'
          | 'AX'
          | 'AZ'
          | 'BA'
          | 'BB'
          | 'BD'
          | 'BE'
          | 'BF'
          | 'BG'
          | 'BH'
          | 'BI'
          | 'BJ'
          | 'BL'
          | 'BM'
          | 'BN'
          | 'BO'
          | 'BQ'
          | 'BR'
          | 'BS'
          | 'BT'
          | 'BW'
          | 'BY'
          | 'BZ'
          | 'CA'
          | 'CC'
          | 'CD'
          | 'CF'
          | 'CG'
          | 'CH'
          | 'CI'
          | 'CK'
          | 'CL'
          | 'CM'
          | 'CN'
          | 'CO'
          | 'CR'
          | 'CU'
          | 'CV'
          | 'CW'
          | 'CX'
          | 'CY'
          | 'CZ'
          | 'DE'
          | 'DJ'
          | 'DK'
          | 'DM'
          | 'DO'
          | 'DZ'
          | 'EC'
          | 'EE'
          | 'EG'
          | 'EH'
          | 'ER'
          | 'ES'
          | 'ET'
          | 'FI'
          | 'FJ'
          | 'FK'
          | 'FM'
          | 'FO'
          | 'FR'
          | 'GA'
          | 'GB'
          | 'GD'
          | 'GE'
          | 'GF'
          | 'GG'
          | 'GH'
          | 'GI'
          | 'GL'
          | 'GM'
          | 'GN'
          | 'GP'
          | 'GQ'
          | 'GR'
          | 'GT'
          | 'GU'
          | 'GW'
          | 'GY'
          | 'HK'
          | 'HN'
          | 'HR'
          | 'HT'
          | 'HU'
          | 'ID'
          | 'IE'
          | 'IL'
          | 'IM'
          | 'IN'
          | 'IO'
          | 'IQ'
          | 'IR'
          | 'IS'
          | 'IT'
          | 'JE'
          | 'JM'
          | 'JO'
          | 'JP'
          | 'KE'
          | 'KG'
          | 'KH'
          | 'KI'
          | 'KM'
          | 'KN'
          | 'KP'
          | 'KR'
          | 'KW'
          | 'KY'
          | 'KZ'
          | 'LA'
          | 'LB'
          | 'LC'
          | 'LI'
          | 'LK'
          | 'LR'
          | 'LS'
          | 'LT'
          | 'LU'
          | 'LV'
          | 'LY'
          | 'MA'
          | 'MC'
          | 'MD'
          | 'ME'
          | 'MF'
          | 'MG'
          | 'MH'
          | 'MK'
          | 'ML'
          | 'MM'
          | 'MN'
          | 'MO'
          | 'MP'
          | 'MQ'
          | 'MR'
          | 'MS'
          | 'MT'
          | 'MU'
          | 'MV'
          | 'MW'
          | 'MX'
          | 'MY'
          | 'MZ'
          | 'NA'
          | 'NC'
          | 'NE'
          | 'NF'
          | 'NG'
          | 'NI'
          | 'NL'
          | 'NO'
          | 'NP'
          | 'NR'
          | 'NU'
          | 'NZ'
          | 'OM'
          | 'PA'
          | 'PE'
          | 'PF'
          | 'PG'
          | 'PH'
          | 'PK'
          | 'PL'
          | 'PM'
          | 'PR'
          | 'PS'
          | 'PT'
          | 'PW'
          | 'PY'
          | 'QA'
          | 'RE'
          | 'RO'
          | 'RS'
          | 'RU'
          | 'RW'
          | 'SA'
          | 'SB'
          | 'SC'
          | 'SD'
          | 'SE'
          | 'SG'
          | 'SH'
          | 'SI'
          | 'SJ'
          | 'SK'
          | 'SL'
          | 'SM'
          | 'SN'
          | 'SO'
          | 'SR'
          | 'SS'
          | 'ST'
          | 'SV'
          | 'SX'
          | 'SY'
          | 'SZ'
          | 'TA'
          | 'TC'
          | 'TD'
          | 'TG'
          | 'TH'
          | 'TJ'
          | 'TK'
          | 'TL'
          | 'TM'
          | 'TN'
          | 'TO'
          | 'TR'
          | 'TT'
          | 'TV'
          | 'TW'
          | 'TZ'
          | 'UA'
          | 'UG'
          | 'US'
          | 'UY'
          | 'UZ'
          | 'VA'
          | 'VC'
          | 'VE'
          | 'VG'
          | 'VI'
          | 'VN'
          | 'VU'
          | 'WF'
          | 'WS'
          | 'XK'
          | 'YE'
          | 'YT'
          | 'ZA'
          | 'ZM'
          | 'ZW'
        )
      | null;
    swift?: string | null;
    /**
     * Tax Registration Number (optional)
     */
    trn?: string | null;
  };
  billingContact?: {
    firstName?: string | null;
    lastName?: string | null;
    countryCode?:
      | (
          | '+93'
          | '+358'
          | '+355'
          | '+213'
          | '+1'
          | '+376'
          | '+244'
          | '+54'
          | '+374'
          | '+297'
          | '+247'
          | '+61'
          | '+43'
          | '+994'
          | '+973'
          | '+880'
          | '+375'
          | '+32'
          | '+501'
          | '+229'
          | '+975'
          | '+591'
          | '+387'
          | '+267'
          | '+55'
          | '+246'
          | '+673'
          | '+359'
          | '+226'
          | '+257'
          | '+855'
          | '+237'
          | '+238'
          | '+599'
          | '+236'
          | '+235'
          | '+56'
          | '+86'
          | '+57'
          | '+269'
          | '+242'
          | '+243'
          | '+682'
          | '+506'
          | '+225'
          | '+385'
          | '+53'
          | '+357'
          | '+420'
          | '+45'
          | '+253'
          | '+593'
          | '+20'
          | '+503'
          | '+240'
          | '+291'
          | '+372'
          | '+268'
          | '+251'
          | '+500'
          | '+298'
          | '+679'
          | '+33'
          | '+594'
          | '+689'
          | '+241'
          | '+220'
          | '+995'
          | '+49'
          | '+233'
          | '+350'
          | '+30'
          | '+299'
          | '+590'
          | '+502'
          | '+44'
          | '+224'
          | '+245'
          | '+592'
          | '+509'
          | '+504'
          | '+852'
          | '+36'
          | '+354'
          | '+91'
          | '+62'
          | '+98'
          | '+964'
          | '+353'
          | '+972'
          | '+39'
          | '+81'
          | '+962'
          | '+7'
          | '+254'
          | '+686'
          | '+383'
          | '+965'
          | '+996'
          | '+856'
          | '+371'
          | '+961'
          | '+266'
          | '+231'
          | '+218'
          | '+423'
          | '+370'
          | '+352'
          | '+853'
          | '+261'
          | '+265'
          | '+60'
          | '+960'
          | '+223'
          | '+356'
          | '+692'
          | '+596'
          | '+222'
          | '+230'
          | '+262'
          | '+52'
          | '+691'
          | '+373'
          | '+377'
          | '+976'
          | '+382'
          | '+212'
          | '+258'
          | '+95'
          | '+264'
          | '+674'
          | '+977'
          | '+31'
          | '+687'
          | '+64'
          | '+505'
          | '+227'
          | '+234'
          | '+683'
          | '+672'
          | '+850'
          | '+389'
          | '+47'
          | '+968'
          | '+92'
          | '+680'
          | '+970'
          | '+507'
          | '+675'
          | '+595'
          | '+51'
          | '+63'
          | '+48'
          | '+351'
          | '+974'
          | '+40'
          | '+250'
          | '+685'
          | '+378'
          | '+239'
          | '+966'
          | '+221'
          | '+381'
          | '+248'
          | '+232'
          | '+65'
          | '+421'
          | '+386'
          | '+677'
          | '+252'
          | '+27'
          | '+82'
          | '+211'
          | '+34'
          | '+94'
          | '+290'
          | '+508'
          | '+249'
          | '+597'
          | '+46'
          | '+41'
          | '+963'
          | '+886'
          | '+992'
          | '+255'
          | '+66'
          | '+670'
          | '+228'
          | '+690'
          | '+676'
          | '+216'
          | '+90'
          | '+993'
          | '+688'
          | '+256'
          | '+380'
          | '+971'
          | '+598'
          | '+998'
          | '+678'
          | '+58'
          | '+84'
          | '+681'
          | '+967'
          | '+260'
          | '+263'
        )
      | null;
    contactNumber?: string | null;
    email?: string | null;
  };
  administrativeContact: {
    firstName: string;
    lastName: string;
    countryCode:
      | '+93'
      | '+358'
      | '+355'
      | '+213'
      | '+1'
      | '+376'
      | '+244'
      | '+54'
      | '+374'
      | '+297'
      | '+247'
      | '+61'
      | '+43'
      | '+994'
      | '+973'
      | '+880'
      | '+375'
      | '+32'
      | '+501'
      | '+229'
      | '+975'
      | '+591'
      | '+387'
      | '+267'
      | '+55'
      | '+246'
      | '+673'
      | '+359'
      | '+226'
      | '+257'
      | '+855'
      | '+237'
      | '+238'
      | '+599'
      | '+236'
      | '+235'
      | '+56'
      | '+86'
      | '+57'
      | '+269'
      | '+242'
      | '+243'
      | '+682'
      | '+506'
      | '+225'
      | '+385'
      | '+53'
      | '+357'
      | '+420'
      | '+45'
      | '+253'
      | '+593'
      | '+20'
      | '+503'
      | '+240'
      | '+291'
      | '+372'
      | '+268'
      | '+251'
      | '+500'
      | '+298'
      | '+679'
      | '+33'
      | '+594'
      | '+689'
      | '+241'
      | '+220'
      | '+995'
      | '+49'
      | '+233'
      | '+350'
      | '+30'
      | '+299'
      | '+590'
      | '+502'
      | '+44'
      | '+224'
      | '+245'
      | '+592'
      | '+509'
      | '+504'
      | '+852'
      | '+36'
      | '+354'
      | '+91'
      | '+62'
      | '+98'
      | '+964'
      | '+353'
      | '+972'
      | '+39'
      | '+81'
      | '+962'
      | '+7'
      | '+254'
      | '+686'
      | '+383'
      | '+965'
      | '+996'
      | '+856'
      | '+371'
      | '+961'
      | '+266'
      | '+231'
      | '+218'
      | '+423'
      | '+370'
      | '+352'
      | '+853'
      | '+261'
      | '+265'
      | '+60'
      | '+960'
      | '+223'
      | '+356'
      | '+692'
      | '+596'
      | '+222'
      | '+230'
      | '+262'
      | '+52'
      | '+691'
      | '+373'
      | '+377'
      | '+976'
      | '+382'
      | '+212'
      | '+258'
      | '+95'
      | '+264'
      | '+674'
      | '+977'
      | '+31'
      | '+687'
      | '+64'
      | '+505'
      | '+227'
      | '+234'
      | '+683'
      | '+672'
      | '+850'
      | '+389'
      | '+47'
      | '+968'
      | '+92'
      | '+680'
      | '+970'
      | '+507'
      | '+675'
      | '+595'
      | '+51'
      | '+63'
      | '+48'
      | '+351'
      | '+974'
      | '+40'
      | '+250'
      | '+685'
      | '+378'
      | '+239'
      | '+966'
      | '+221'
      | '+381'
      | '+248'
      | '+232'
      | '+65'
      | '+421'
      | '+386'
      | '+677'
      | '+252'
      | '+27'
      | '+82'
      | '+211'
      | '+34'
      | '+94'
      | '+290'
      | '+508'
      | '+249'
      | '+597'
      | '+46'
      | '+41'
      | '+963'
      | '+886'
      | '+992'
      | '+255'
      | '+66'
      | '+670'
      | '+228'
      | '+690'
      | '+676'
      | '+216'
      | '+90'
      | '+993'
      | '+688'
      | '+256'
      | '+380'
      | '+971'
      | '+598'
      | '+998'
      | '+678'
      | '+58'
      | '+84'
      | '+681'
      | '+967'
      | '+260'
      | '+263';
    contactNumber: string;
    email: string;
  };
  faqs?: string | null;
  termsConditions?: string | null;
  cancellationPolicy?: string | null;
  comments?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  country:
    | 'AC'
    | 'AD'
    | 'AE'
    | 'AF'
    | 'AG'
    | 'AI'
    | 'AL'
    | 'AM'
    | 'AO'
    | 'AR'
    | 'AS'
    | 'AT'
    | 'AU'
    | 'AW'
    | 'AX'
    | 'AZ'
    | 'BA'
    | 'BB'
    | 'BD'
    | 'BE'
    | 'BF'
    | 'BG'
    | 'BH'
    | 'BI'
    | 'BJ'
    | 'BL'
    | 'BM'
    | 'BN'
    | 'BO'
    | 'BQ'
    | 'BR'
    | 'BS'
    | 'BT'
    | 'BW'
    | 'BY'
    | 'BZ'
    | 'CA'
    | 'CC'
    | 'CD'
    | 'CF'
    | 'CG'
    | 'CH'
    | 'CI'
    | 'CK'
    | 'CL'
    | 'CM'
    | 'CN'
    | 'CO'
    | 'CR'
    | 'CU'
    | 'CV'
    | 'CW'
    | 'CX'
    | 'CY'
    | 'CZ'
    | 'DE'
    | 'DJ'
    | 'DK'
    | 'DM'
    | 'DO'
    | 'DZ'
    | 'EC'
    | 'EE'
    | 'EG'
    | 'EH'
    | 'ER'
    | 'ES'
    | 'ET'
    | 'FI'
    | 'FJ'
    | 'FK'
    | 'FM'
    | 'FO'
    | 'FR'
    | 'GA'
    | 'GB'
    | 'GD'
    | 'GE'
    | 'GF'
    | 'GG'
    | 'GH'
    | 'GI'
    | 'GL'
    | 'GM'
    | 'GN'
    | 'GP'
    | 'GQ'
    | 'GR'
    | 'GT'
    | 'GU'
    | 'GW'
    | 'GY'
    | 'HK'
    | 'HN'
    | 'HR'
    | 'HT'
    | 'HU'
    | 'ID'
    | 'IE'
    | 'IL'
    | 'IM'
    | 'IN'
    | 'IO'
    | 'IQ'
    | 'IR'
    | 'IS'
    | 'IT'
    | 'JE'
    | 'JM'
    | 'JO'
    | 'JP'
    | 'KE'
    | 'KG'
    | 'KH'
    | 'KI'
    | 'KM'
    | 'KN'
    | 'KP'
    | 'KR'
    | 'KW'
    | 'KY'
    | 'KZ'
    | 'LA'
    | 'LB'
    | 'LC'
    | 'LI'
    | 'LK'
    | 'LR'
    | 'LS'
    | 'LT'
    | 'LU'
    | 'LV'
    | 'LY'
    | 'MA'
    | 'MC'
    | 'MD'
    | 'ME'
    | 'MF'
    | 'MG'
    | 'MH'
    | 'MK'
    | 'ML'
    | 'MM'
    | 'MN'
    | 'MO'
    | 'MP'
    | 'MQ'
    | 'MR'
    | 'MS'
    | 'MT'
    | 'MU'
    | 'MV'
    | 'MW'
    | 'MX'
    | 'MY'
    | 'MZ'
    | 'NA'
    | 'NC'
    | 'NE'
    | 'NF'
    | 'NG'
    | 'NI'
    | 'NL'
    | 'NO'
    | 'NP'
    | 'NR'
    | 'NU'
    | 'NZ'
    | 'OM'
    | 'PA'
    | 'PE'
    | 'PF'
    | 'PG'
    | 'PH'
    | 'PK'
    | 'PL'
    | 'PM'
    | 'PR'
    | 'PS'
    | 'PT'
    | 'PW'
    | 'PY'
    | 'QA'
    | 'RE'
    | 'RO'
    | 'RS'
    | 'RU'
    | 'RW'
    | 'SA'
    | 'SB'
    | 'SC'
    | 'SD'
    | 'SE'
    | 'SG'
    | 'SH'
    | 'SI'
    | 'SJ'
    | 'SK'
    | 'SL'
    | 'SM'
    | 'SN'
    | 'SO'
    | 'SR'
    | 'SS'
    | 'ST'
    | 'SV'
    | 'SX'
    | 'SY'
    | 'SZ'
    | 'TA'
    | 'TC'
    | 'TD'
    | 'TG'
    | 'TH'
    | 'TJ'
    | 'TK'
    | 'TL'
    | 'TM'
    | 'TN'
    | 'TO'
    | 'TR'
    | 'TT'
    | 'TV'
    | 'TW'
    | 'TZ'
    | 'UA'
    | 'UG'
    | 'US'
    | 'UY'
    | 'UZ'
    | 'VA'
    | 'VC'
    | 'VE'
    | 'VG'
    | 'VI'
    | 'VN'
    | 'VU'
    | 'WF'
    | 'WS'
    | 'XK'
    | 'YE'
    | 'YT'
    | 'ZA'
    | 'ZM'
    | 'ZW';
  city: string;
  harbour: string;
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  blobUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routes".
 */
export interface Route {
  id: string;
  routeName: string;
  location: string | Location;
  hourRoutes?:
    | {
        /**
         * Enter duration in hours (e.g., "3 Hours", "6-8 Hours")
         */
        duration: string;
        points?:
          | {
              point: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-types".
 */
export interface EventType {
  id: string;
  label: string;
  /**
   * URL-friendly identifier (auto-generated if left empty)
   */
  slug: string;
  /**
   * 1 = first, 2 = second, 3 = third, etc.
   */
  priority: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "extras".
 */
export interface Extra {
  id: string;
  category: 'watersports' | 'catering' | 'entertainment' | 'decor';
  name: string;
  /**
   * Detailed description of the extra service
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  itemsDetails: string | Media;
  minimumNumberOfPax: {
    min: number;
    max?: number | null;
  };
  unitPrice: number;
  /**
   * Select extras that must be purchased with this item
   */
  dependentItems?: (string | Extra)[] | null;
  boat: (string | Boat)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: string;
  code: string;
  type: 'percentage' | 'fixed';
  amount: number;
  isActive?: boolean | null;
  expiresAt?: string | null;
  usageCount?: number | null;
  applyToAllBoats?: boolean | null;
  /**
   * If not global, select which boats this coupon applies to.
   */
  boats?: (string | Boat)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boat-types".
 */
export interface BoatType {
  id: string;
  label: string;
  /**
   * URL-friendly identifier (auto-generated if left empty)
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: string;
  title: string;
  subtitle?: string | null;
  backgroundImage: string | Media;
  ctaText?: string | null;
  ctaLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: string;
  logo: string | Media;
  /**
   * Logo to display when user scrolls down
   */
  scrolled_logo?: (string | null) | Media;
  menu_items: {
    label: string;
    link: string;
    submenu?:
      | {
          label: string;
          link: string;
          /**
           * If ON, this submenu navigates to a filter landing page
           */
          acts_as_filter?: boolean | null;
          filter_kind?: ('event' | 'type' | 'harbour') | null;
          /**
           * Exact value as used in your filters (e.g., "Watersports", "Yacht", "Dubai Marina")
           */
          filter_value?: string | null;
          /**
           * Pretty URL slug (e.g., "watersports", "yachts", "dubai-marina"). Used for /[filter] route.
           */
          filter_slug?: string | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  social_media?:
    | {
        platform: string;
        url: string;
        /**
         * Font Awesome icon class (e.g. fab fa-facebook)
         */
        icon: string;
        id?: string | null;
      }[]
    | null;
  book_now_button: {
    label: string;
    link: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo: string | Media;
  footer_links: {
    label: string;
    link: string;
    id?: string | null;
  }[];
  social_links?:
    | {
        platform: string;
        icon: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  copyright: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'admin' | 'user';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  boat: string | Boat;
  user: string | User;
  rating: number;
  comment?: string | null;
  /**
   * Approved reviews will be visible publicly
   */
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter email subscribers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: string;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'reservations';
        value: string | Reservation;
      } | null)
    | ({
        relationTo: 'owners';
        value: string | Owner;
      } | null)
    | ({
        relationTo: 'boats';
        value: string | Boat;
      } | null)
    | ({
        relationTo: 'event-types';
        value: string | EventType;
      } | null)
    | ({
        relationTo: 'boat-types';
        value: string | BoatType;
      } | null)
    | ({
        relationTo: 'extras';
        value: string | Extra;
      } | null)
    | ({
        relationTo: 'hero';
        value: string | Hero;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'menu';
        value: string | Menu;
      } | null)
    | ({
        relationTo: 'footer';
        value: string | Footer;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'routes';
        value: string | Route;
      } | null)
    | ({
        relationTo: 'locations';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: string | Subscriber;
      } | null)
    | ({
        relationTo: 'coupons';
        value: string | Coupon;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  boat?: T;
  departureLocation?: T;
  paymentMethod?: T;
  numberOfInstallments?: T;
  downPaymentAmount?: T;
  guests?: T;
  user?: T;
  guestEmail?: T;
  countryCode?: T;
  guestPhone?: T;
  startTime?: T;
  endTime?: T;
  status?: T;
  paymentLinkId?: T;
  paymentLink?: T;
  totalPrice?: T;
  method?: T;
  payments?:
    | T
    | {
        id?: T;
        kind?: T;
        installmentStage?: T;
        createdAt?: T;
        installedAt?: T;
        paidAt?: T;
        amount?: T;
        method?: T;
        date?: T;
        status?: T;
        balance?: T;
        paymentLink?: T;
        paymentLinkId?: T;
        notes?: T;
      };
  transactionId?: T;
  specialRequests?: T;
  extras?:
    | T
    | {
        extra?: T;
        quantity?: T;
        unitPrice?: T;
        id?: T;
      };
  otherExtras?:
    | T
    | {
        name?: T;
        price?: T;
        quantity?: T;
        id?: T;
      };
  coupon?: T;
  couponCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "owners_select".
 */
export interface OwnersSelect<T extends boolean = true> {
  name?: T;
  countryCode?: T;
  contactNumber?: T;
  address?:
    | T
    | {
        streetLine1?: T;
        streetLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  email?: T;
  bankDetails?:
    | T
    | {
        accountName?: T;
        iban?: T;
        bankName?: T;
        country?: T;
        swift?: T;
        trn?: T;
      };
  billingContact?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        countryCode?: T;
        contactNumber?: T;
        email?: T;
      };
  administrativeContact?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        countryCode?: T;
        contactNumber?: T;
        email?: T;
      };
  faqs?: T;
  termsConditions?: T;
  cancellationPolicy?: T;
  comments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boats_select".
 */
export interface BoatsSelect<T extends boolean = true> {
  slug?: T;
  owner?: T;
  name?: T;
  location?: T;
  price?: T;
  salePrice?: T;
  priceDay?: T;
  minHours?: T;
  advancedMinHours?:
    | T
    | {
        ruleType?: T;
        days?: T;
        timeRange?:
          | T
          | {
              type?: T;
              startTime?: T;
              endTime?: T;
            };
        minHours?: T;
        specialEventName?: T;
        dateMode?: T;
        startDate?: T;
        endDate?: T;
        packageHours?: T;
        packagePrice?: T;
        id?: T;
      };
  boatSpecifications?:
    | T
    | {
        type?: T;
        manufacture?: T;
        refit?: T;
        length?: T;
        capacity?: T;
        sleeps?: T;
        bathrooms?: T;
        crew?: T;
        description?: T;
      };
  keyFeatures?:
    | T
    | {
        feature?: T;
        included?: T;
        id?: T;
      };
  amenities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  additionalServices?:
    | T
    | {
        service?: T;
        file?: T;
        price?: T;
        id?: T;
      };
  routes?: T;
  media?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  boatSpecific?:
    | T
    | {
        faq?: T;
        id?: T;
      };
  discounts?:
    | T
    | {
        type?: T;
        variable?: T;
        amount?: T;
        startDate?: T;
        endDate?: T;
        id?: T;
      };
  surgePricing?: T;
  averageRating?: T;
  reviewCount?: T;
  specialEventTags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-types_select".
 */
export interface EventTypesSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boat-types_select".
 */
export interface BoatTypesSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "extras_select".
 */
export interface ExtrasSelect<T extends boolean = true> {
  category?: T;
  name?: T;
  description?: T;
  itemsDetails?: T;
  minimumNumberOfPax?:
    | T
    | {
        min?: T;
        max?: T;
      };
  unitPrice?: T;
  dependentItems?: T;
  boat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  backgroundImage?: T;
  ctaText?: T;
  ctaLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blobUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  logo?: T;
  scrolled_logo?: T;
  menu_items?:
    | T
    | {
        label?: T;
        link?: T;
        submenu?:
          | T
          | {
              label?: T;
              link?: T;
              acts_as_filter?: T;
              filter_kind?: T;
              filter_value?: T;
              filter_slug?: T;
              id?: T;
            };
        id?: T;
      };
  social_media?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  book_now_button?:
    | T
    | {
        label?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  footer_links?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  social_links?:
    | T
    | {
        platform?: T;
        icon?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routes_select".
 */
export interface RoutesSelect<T extends boolean = true> {
  routeName?: T;
  location?: T;
  hourRoutes?:
    | T
    | {
        duration?: T;
        points?:
          | T
          | {
              point?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  country?: T;
  city?: T;
  harbour?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  boat?: T;
  user?: T;
  rating?: T;
  comment?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  amount?: T;
  isActive?: T;
  expiresAt?: T;
  usageCount?: T;
  applyToAllBoats?: T;
  boats?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}